package huangzihao.homework.multidatasource.mapper;

import huangzihao.homework.multidatasource.entity.Goods;
import org.apache.ibatis.annotations.*;

@Mapper
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Tue Jan 05 21:20:40 CST 2021
     */
    @Delete({
        "delete from GOODS",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Tue Jan 05 21:20:40 CST 2021
     */
    @Insert({
        "insert into GOODS (NAME, DESCRIPTION, ",
        "STATUS, PRICE, CCY, ",
        "INVENTORY, CREATE_TIME, ",
        "UPDATE_TIME)",
        "values (#{name,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=CHAR}, #{price,jdbcType=DECIMAL}, #{ccy,jdbcType=VARCHAR}, ",
        "#{inventory,jdbcType=INTEGER}, #{createTime,jdbcType=BIGINT}, ",
        "#{updateTime,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Tue Jan 05 21:20:40 CST 2021
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Tue Jan 05 21:20:40 CST 2021
     */
    @Select({
        "select",
        "ID, NAME, DESCRIPTION, STATUS, PRICE, CCY, INVENTORY, CREATE_TIME, UPDATE_TIME",
        "from GOODS",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("huangzihao.homework.multidatasource.mapper.GoodsMapper.BaseResultMap")
    Goods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Tue Jan 05 21:20:40 CST 2021
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbg.generated Tue Jan 05 21:20:40 CST 2021
     */
    @Update({
        "update GOODS",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "DESCRIPTION = #{description,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=CHAR},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "CCY = #{ccy,jdbcType=VARCHAR},",
          "INVENTORY = #{inventory,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=BIGINT},",
          "UPDATE_TIME = #{updateTime,jdbcType=BIGINT}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Goods record);
}