#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3307/emall
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

#Master DataSource Config
spring:
  master:
    jdbc-url: jdbc:mysql://127.0.0.1:3307/emall
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  slave1:
    jdbc-url: jdbc:mysql://127.0.0.1:3308/emall
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  slave2:
    jdbc-url: jdbc:mysql://127.0.0.1:3309/emall
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: huangzihao.homework.multidatasource.mapper